version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "http-api-lambda-proxy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l1jcu44qrwgl"
s3_prefix = "http-api-lambda-proxy"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
tags = "Project=\"http-api-lambda-proxy\" Author=\"Greg Davis\" SourceCodeUrl=\"https://github.com/gadavis2/http-api-lambda-proxy\""
parameter_overrides = "ApiName=\"http-api-lambda-proxy\""
