version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "http-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1l1jcu44qrwgl"
s3_prefix = "http-api"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LambdaFunction=\"api-get-badges-function\""
